# Generated by Django 3.2.6 on 2021-09-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210914_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='nom_departement',
        ),
    ]
