# Generated by Django 3.2.6 on 2021-09-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_nom_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nom_departement',
            field=models.ForeignKey(default='Informatique', on_delete=django.db.models.deletion.CASCADE, to='employee.departement'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(default='Informatique', max_length=255),
        ),
    ]
